# Perfil de desarrollo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactivar cache de Thymeleaf para ver cambios inmediatos
spring.thymeleaf.cache=false
