spring.application.name=SCLI

# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/BD_Laboratorio1

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
# validate: valida el mapeo contra tu BD sin modificarla
# update: (solo dev) crea/actualiza tablas en caliente
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# (En Hibernate 6/Boot 3 se autodetecta el dialect, pero dejarlo explícito no molesta)

# --- Servidor ---
server.port=8081


spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**

# --- Thymeleaf ---
# Estos dos NO son necesarios con Thymeleaf y pueden confundir; elimínalos:
# spring.mvc.view.prefix=classpath:/templates/
# spring.mvc.view.suffix=.html
# (Opcional) En dev:
spring.thymeleaf.cache=false

# --- Errores (útil para debug) ---
server.error.include-message=always
server.error.include-binding-errors=always
spring.web.resources.static-locations=classpath:/static/

# --- Recursos estáticos ---
# Ya es el default; puedes removerlo. Si lo dejas, OK.
# spring.web.resources.static-locations=classpath:/static/

spring.mvc.hiddenmethod.filter.enabled=true
logging.level.com.uteq.SCLI=INFO

#------------------------------
# Email configuration   
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true
app.mail.from=Sistema de Control de Laboratorios <${spring.mail.username:no-reply@scli.local}>
app.mail.enabled=true
spring.mail.properties.mail.smtp.localhost=scli.local

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE