# Perfil de producción
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Mantener cache de Thymeleaf para mejorar rendimiento
spring.thymeleaf.cache=true